### ISSUE TITLE
Answer Units Duplication

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#100]
Findings:
1. If there are multiple answers with an accepted one, all answers will show up as a separate answer unit. If there is an accepted answer, it will show up twice. 
2. If there are multiple answers without an accepted one, all answers will show up as a separate answer unit. But the last answer will show up twice. My guess is that Lucy thinks that is an accepted one.(based on finding 2 and 3, if we can collapse the answers, that would be great! For accepted ones, it can have some tag for indication)
3. Special case: ask "expanding root drive in stack" in Lucy, both answers showed up twice. 

They are all duplicated answers, they will be addressed.

**Comment by LucyPilot** [comment]
We need to give Equals 3 team a clear answer on if we want to bring in all answers or just accepted answers. If we bring all answers, how to display them as answer units.

**Comment by LucyPilot** [comment]
The decision is to bring all the answers to Lucy. For the accepted answer, we would like to have the indication like you showed us. But can we make it stand out more? For example, make the color to green, like what AnswerHub does?

**Comment by MikeMoravec45** [comment]
Did not mean to close. This work is done and available in production today. Please verify and close.
![image](https://user-images.githubusercontent.com/50464703/72008290-1bc9c280-3219-11ea-870d-541fb24e1d86.png)

**Comment by LucyPilot** [comment]
Apparently, no matter what question I asks, it shows me the same answer from AnswerHub. For example,  
![image](https://user-images.githubusercontent.com/50414677/72015744-568b2500-3230-11ea-9804-31ebb24cd3c0.png)

**Comment by LucyPilot** [comment]
This is fixed.
