### ISSUE TITLE
Too much relevancy between irrelevant questions

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#109]
As I start rating some files as an accurate answer to some specific questions, those files show up as answer units in other questions as well, but they are not the accurate answer to those ones. Somehow, Lucy wants to give you all the file that has higher rating scores regardless of what questions you ask. For example, what are the main features in cloud? Cloud Dojo, NW Products Cloud Solution Products showed up as answer units as well. They are not relevant. I gave Cloud Dojo a rating of 1, didn't rate down the other one just in case you want to test.

**Comment by MikeMoravec45** [comment]
The work in LAD-2450 will also impact this. One thing to consider is if you asked a random person your example: "what are the main features in cloud?", they would likely consider "Cloud Dojo, NW Products Cloud Solution Products" relevant responses.
