### ISSUE TITLE
Define workflow

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#20]
If question not answered.  Can users now type comments in a popup?  Can we start routing to an email list.

**Comment by LucyPilot** [comment]
Today is manual fwd, by end of May they will have automated fwd, by end of June they will have the comment box.

**Comment by LucyPilot** [comment]
This is coming next week. Users will be able to put comments

**Comment by MikeMoravec45** [comment]
Future discussion: attach files in addition to comment?

**Comment by Zach-Meierhofer-Equals-3** [comment]
![image](https://user-images.githubusercontent.com/50880770/58113068-64653a80-7bba-11e9-90ee-61129d39769f.png)

**Comment by Zach-Meierhofer-Equals-3** [comment]
![image](https://user-images.githubusercontent.com/50880770/58113107-76df7400-7bba-11e9-854a-6a4bffadeff4.png)

**Comment by MikeMoravec45** [comment]
Users can enter comments today. Automated forwarding to SME team of Manual Lucy Assists is currently prioritized to be completed in the next 30 days. Until then, I will continue manually forwarding them.

**Comment by Zach-Meierhofer-Equals-3** [comment]
Automated forwarding ticket:
LAD-1581 Send Lucy Assists from team to select users
