### ISSUE TITLE
Timeline for Lucy to understand excels

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#22]
We have a lot of excel files that we need to manually convert to pdf now.

**Comment by LucyPilot** [comment]
Equal 3 is testing over the next few weeks, targeting end of May mid-June. Right now, Equal 3 won't auto inject excel files. We need to send them the file and they will train it.

**Comment by MikeMoravec45** [comment]
Development ticket will be worked on in the next 2 weeks. At that point, we will begin testing the results.

**Comment by Zach-Meierhofer-Equals-3** [comment]
First round of work has been done on this. We are doing testing on our end to see how the results are performing. Will have an update soon.

**Comment by MikeMoravec45** [comment]
Initial testing has produced mixed results. The tool breaks excel sheets at the width of the total columns with data in them. So sheets with more columns will give a more zoomed out view of the sheet and can be too small to read. I can go over this in our next meeting. Some results show pretty well though.

**Comment by MikeMoravec45** [comment]
We have turned on xlsx capabilities for Nationwide Demo results to do some tests with your team.

**Comment by MikeMoravec45** [comment]
Closing this ticket as we have built this functionality and can continue testing files.
