### ISSUE TITLE
Lucy doesn't show new questions after 10 on the home screen

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#23]
In the Lucy question bar, it shows historic questions asked, but after 10 or so, it stops showing the recently asked questions.  It appears you could scroll down to see them, but you can't.

**Comment by LucyPilot** [comment]
They will fix this by end of May

**Comment by Zach-Meierhofer-Equals-3** [comment]
LAD-1767 Homepage - Your Research - Expand Past 10 Recent Q's

Ticket is created.

**Comment by MikeMoravec45** [comment]
LAD-1767

**Comment by MikeMoravec45** [comment]
This is built and tested. Pending migration.

**Comment by LucyPilot** [comment]
This is in prod.
