### ISSUE TITLE
Typeable page for pagination

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#27]
Can we have some input field to put what page user want to directly jump to instead of navigating one by one?

**Comment by Zach-Meierhofer-Equals-3** [comment]
This ticket has been created and is currently slated to be in the the sprint beginning next week.

**Comment by Zach-Meierhofer-Equals-3** [comment]
LAD-1716 Pagination | Add Select Page Option

**Comment by Zach-Meierhofer-Equals-3** [comment]
This item has been prioritized for the upcoming sprint and is already being worked on by our UI team

**Comment by MikeMoravec45** [comment]
This is done in our testing environment and should be in production by next Monday
