### ISSUE TITLE
Video function issues

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#32]
- [ ] Videos are sliced into pages. For example, page 1 is from 0:00, page 2 is from 0:14. But my answer is starting from 0:07. How can I rate it from 0:07. 
- [ ] When I click into the video and play, it is always defaulted to mute. Can we have it to be unmute as soon as I start playing the video? Because sometimes, after I change the volume, the answer is already played. 
- [x] Auto scrolling is not working after I click into the video. It seems like the video component doesn’t have scrolling enabled. But if I hover my mouse on the title or the scrolling bar, I can scroll up and down. Use the scrolling hovering over outside of the video itself. If you scroll inside of the video, that controls the volume up and down.
- [ ] If I am already in the video answer unit, and noticed that keyword is unchecked. After I check it, and click some specific keyword to play the keyword from when it shows in the video, it always play the end of the video. 
- [ ] When I ask the question later again, the video keyword setting is off even after I set it to all insights view from step 1. 
- [ ] By default, keyword is always set to off. 
- [ ] Translation function is flaky

**Comment by LucyPilot** [comment]
For the third issue, Use the scrolling hovering over outside of the video itself. If you scroll inside of the video, that controls the volume up and down.

**Comment by LucyPilot** [comment]
Mike is researching for all the rest.

**Comment by Zach-Meierhofer-Equals-3** [comment]
"_When I ask the question later again, the video keyword setting is off even after I set it to all insights view from step 1.
  By default, keyword is always set to off."_
LAD-1649 Videos should default to include keywords

**Comment by Zach-Meierhofer-Equals-3** [comment]
There is a separate issue we have regarding videos that should hopefully address some of these issues 
LAD-1646 Videos Require Clicking Twice
