### ISSUE TITLE
Auto logout users if they close windows or end of the day

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#35]
Logout always helps solve performance and caching problems. If we could auto-logout users when they close the window or at the end of the day, that would be ideal so that users don't have to remember to logout every day.

**Comment by LucyPilot** [comment]
#37 #36 are related to this. Combined all three together.

**Comment by LucyPilot** [comment]
This is our first priority. Equal 3 team is working on this. Updates will be provided next week.

**Comment by Zach-Meierhofer-Equals-3** [comment]
Ticket is created, and prioritized for the current sprint.

**Comment by Zach-Meierhofer-Equals-3** [comment]
ticket: 
LAD-1617 Logout after inactivity

**Comment by MikeMoravec45** [comment]
Ticket is In Progress. Resolution date TBD.

**Comment by MikeMoravec45** [comment]
Ticket is complete and code will be pushed to production in the next week.
