### ISSUE TITLE
Training ACRONYMS.pdf

### ISSUE THREAD

**Issue by AliciaKohler** [LucyPilot/Issues-Tracking#40]
I was working on training for ACRONYMS.pdf, I was not having much luck searching for information in this document. I started on the last page and was moving backwards searching for different acronyms. I tried re-wording my questions. Can you work on tuning this similar to what you did with the NW Business Glossary from inside.pdf.

**Comment by MikeMoravec45** [comment]
We've got a trainer working on this today.

**Comment by MikeMoravec45** [comment]
This training has been completed.
