### ISSUE TITLE
Auto-route a question with low confidence level answers to support team

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#43]
Pilot team asked why Lucy doesn't give them a choice to ask for help but automatically route them to support team if the answers' confidence level is under the threshold. Any reason why this behaves different for asking help? Is it possible to change it to the way that user makes the choice?

**Comment by LucyPilot** [comment]
They built this feature because some of the clients are relying on auto-routing instead of providing feedback. We will have a discussion about this and see if this is something we truly not need. If the whole team wants to remove this feature, Equal 3 will work on removing it from our instance.

**Comment by LucyPilot** [comment]
The team decides to remove this feature. Users should always have the option to route to support team. If all answers are lower than 35%, the message will still say Lucy didn't find an answer to your question. But with a choice for user to route to support team or not.

**Comment by Zach-Meierhofer-Equals-3** [comment]
Ticket has been created. 

LAD-1753 Manage Company - Toggle Automatic Lucy Assist

It will be a toggle-able feature should we want to re-add it in the future

**Comment by MikeMoravec45** [comment]
This is prioritized to be completed in August.

**Comment by MikeMoravec45** [comment]
This is completed.No longer auto-routing for Nationwide.
