### ISSUE TITLE
Observations for testing Lucy's understanding of files

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#45]
1. General Word testing
- Didn’t pick up coding standards
- Inconsistent with responses – sometimes get very good responses for the questions and sometimes not. 

2. General PPT Testing
Does not search inside PPTs, Got response only if the question had a matching word in the title of the ppt file. 
 
3. PDF Testing 
- Didn’t answer questions on distributions at first and then pulled up the answers
- Very inconsistent from the previous experience on pdfs

4. Other- Some captures of what I received for the questions which didn’t make sense to me. 
 
Not sure why I got the message below, without really getting any relevant answer

![Lucy error](https://user-images.githubusercontent.com/50414677/57873548-89356880-77dc-11e9-9068-4487ed019138.png)

**Comment by LucyPilot** [comment]
Team provided a very good feedback during standup. They found out that Lucy understands videos very good and provides great answers. But for other tech docs, maybe because of the format or special terms, Lucy doesn’t understand them well. Is there any back-end training or some best practices we can follow to make Lucy understand those better?

**Comment by LucyPilot** [comment]
#44 is related to first observation from the list.

**Comment by LucyPilot** [comment]
For Ruby Testing Script:
Q: How to write testing scenario for testing invalid input
One of the answers with a title "p Perfoming a Smoke Test ...." showed up. But it is not related to the question at all. Do we know the reason why Lucy picked that and showed it? This is similar to other observations we had. Some of the answers are not related at all but showed up.

**Comment by LucyPilot** [comment]
From Sylaja: "I got good results from the ppt testing specific to acquisitions similar to Roma. I opened the other ppt from onboarding folder to see if its text or images possibly contributing to the poor results. Its text primarily in both. I now wonder if the ppt in the onboarding folder is corrupted or its a different version"

**Comment by MikeMoravec45** [comment]
E3 Trainers are in the midst of testing. Will follow up with results soon.

**Comment by MikeMoravec45** [comment]
Hi Gem,
Overall, the training team reports that Lucy performed much better with natural language and less so with numbers and code (which makes sense as that is the central value prop of Lucy). In addition to videos, your PPTs and PDFs worked well as long as they contain natural language. 

There is a reduction in accuracy when Lucy searches for code and attempts to distinguish between numbers (1051 Report vs 1051a Report); however, over time Lucy's performance will improve via the training your team is providing, as she begins to better understand Nationwide's specific domains such as coding. 

To the question of "Is there any back-end training or some best practices we can follow to make Lucy understand those better?", there are 3 main things.

1. Apply business glossaries. We did this on May 21st and you should have seen some uptick in confidence scores and results after that. 
2. Collect user behavior information (types of questions, which answers are being clicked, etc) to improve understanding and confidence over time. 
3. Train broadly - train a few questions from as many different types of documents/folders/use cases as possible. Doing this is better than training a small amount of documents heavily. The latter approach can give excessive weighting to a narrow subset of your content.

Additionally, I will have my team further investigate the items you raised in regards to your testing of PDF / PPT documents. This is the first time we've had this issue presented by a customer and there are several factors involved; I will let you know of our findings to be conducted next week. 

For any specific files that you are not finding, let's have a ticket for each one, so we can close each once they are found.
