### ISSUE TITLE
Weird issue and Double scrolling bar

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#46]
"What are Lucy out of box metrics" is always showing up on the left panel even after I logout and clear my cache. It was fixed after I reset my password. But now it comes back again. 

![Lucy error 1](https://user-images.githubusercontent.com/50414677/57883240-a295df00-77f3-11e9-9810-5345c9ac4037.PNG)

Also, after half an hour usage of Lucy, an error happened and asked me to refresh my page. I refreshed my page, and then I started to see double scrolling bar again.

**Comment by LucyPilot** [comment]
I had these two issues happened to me randomly:
- Occasional double scroll bar (in backlog) 
- Blank suggestions expansion in dialog box (dev in progress)
They are not impacting Lucy performance. But they are the annoying things for users

**Comment by MikeMoravec45** [comment]
Tickets are being prioritized in our backlog:

LAD-1618 Double Scroll Bar
LAD-798 Blank suggestions expansion

**Comment by MikeMoravec45** [comment]
Blank suggestions is fixed in our testing environment. On track to be in production by next Monday.

**Comment by MikeMoravec45** [comment]
Double scroll bar will be pushed next week.

**Comment by MikeMoravec45** [comment]
This is currently scheduled to be in Production before next Monday
