### ISSUE TITLE
Lucy behaviors towards business glossary 

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#49]
Business glossary pdf shows as an answer if I search for acronyms. Mike has manually injected business glossary. If all the terms are in Lucy, will Lucy show up the definition of the acronym at the top like what google does today?

**Comment by MikeMoravec45** [comment]
The manual effort helps Lucy understand what you are searching and should improve your search results. It will not create a new answer unit (like the example you gave from google)
