### ISSUE TITLE
Can file name be taken into consideration for Lucy search?

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#57]
Sometimes, the title or file name has the keyword that I ask for. But the content doesn't contain the keyword. Lucy won't find me the correct answer because she doesn't understand file names.

**Comment by MikeMoravec45** [comment]
We are currently in the design stage of building out that functionality.

**Comment by MikeMoravec45** [comment]
This is still front of mind and being explored. I will keep you posted as I know more.

**Comment by LucyPilot** [comment]
This is in prod. Very nice feature!
