### ISSUE TITLE
Options to choose a backend help disappears occasionally

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#63]
I routed one question to Lucy support. When I wanted to route another question to Lucy support, I didn't see the options for me to choose. I asked couple different questions and then refreshed the page, it didn't solve the issue. After couple tries, I finally got it back.

**Comment by LucyPilot** [comment]
[Questionair is missing from Lucy.zip](https://github.com/LucyPilot/Issues-Tracking/files/3281540/Questionair.is.missing.from.Lucy.zip)

**Comment by MikeMoravec45** [comment]
LAD-1885
Ticket created, will prioritize in an upcoming sprint.

**Comment by MikeMoravec45** [comment]
This has been fixed and is scheduled to be pushed to production before Monday
