### ISSUE TITLE
Can't page through

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#64]
Couldn't change pages to rate. This is happening on all the multiple-page files as I see. I attached the video here.
[Paging through issues.zip](https://github.com/LucyPilot/Issues-Tracking/files/3281551/Paging.through.issues.zip)

**Comment by MikeMoravec45** [comment]
LAD-1828
This issue is in progress. Will provide updates when available.

**Comment by MikeMoravec45** [comment]
This is done in production
