### ISSUE TITLE
Excel content is too small

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#67]
I have adjusted the column width for Rocket Chat folder in Box account. But all the excels are still showing super small as the answer. Not sure what the problem is. There are a lot of excels having the same issue.

**Comment by MikeMoravec45** [comment]
LAD-1928 created to limit the row count included in an answer unit to 25. Will be prioritized in Q3

**Comment by LucyPilot** [comment]
Some excels, they have a lot of columns and rows, but they still turn out to be clear as answer units. What is the difference? Can we figure out what the following answers show up clear? Maybe we can apply this to all other excel files?
Here are the questions with clear excel answer units:
1. When did DPIM features turned in production
2. What is the transaction method for repayment cleared suspense
3. What is the role for billings admin in Nationwide Cloud

**Comment by MikeMoravec45** [comment]
Thank you for that detail. That will be helpful when they are exploring solutions in Q3

**Comment by MikeMoravec45** [comment]
A solution for this is ready to be deployed. Estimated date October 11th.

**Comment by LucyPilot** [comment]
This is in prod.
