### ISSUE TITLE
Lucy is under too much load error

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#68]
I got this error as I attached. After I refreshed the page, it shows the double scrolling bar and Lucy still doesn't work. Then I logged out and re-login. It still shows the error.
![new error](https://user-images.githubusercontent.com/50414677/59696859-d2515180-91ba-11e9-849f-ff9f959bc249.PNG)

**Comment by MikeMoravec45** [comment]
LAD-1895 In Progress

**Comment by MikeMoravec45** [comment]
This is now fixed in production

**Comment by LucyPilot** [comment]
I got this error back again. Don't know how to recreate it yet. 
![Lucy too much load issues](https://user-images.githubusercontent.com/50414677/63522600-b02fc480-c4c6-11e9-8890-36f645ea164e.PNG)

**Comment by LucyPilot** [comment]
This showed up this morning when I was demoing to CIO again. After I filter by different metadata couple times, it shows me this error.

**Comment by LucyPilot** [comment]
I recommend to keep opening separate windows for Lucy and constantly asking questions to load a lot of videos. A question like "what is dojo to go" will probably help to recreate the issue.

**Comment by LucyPilot** [comment]
I haven't seen this error for a while.
