### ISSUE TITLE
Lucy shows 0 of 0 results for some tested questions

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#69]
We are experiencing an issue with Lucy Research for questions and content that worked for us before is now showing up now.

**Comment by LucyPilot** [comment]
From Mike's response: "There are a number of questions that are firing 0 of 0 results. While other questions still work, there is a subset that just will not work right now. I have a ticket (LAD-1918) to address this, but it will unfortunately not be resolved immediately."

**Comment by MikeMoravec45** [comment]
This is fixed now. It just needs to be promoted to production (in the next week)
