### ISSUE TITLE
Lucy 0% searching progress keeps pinning 

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#70]
It happens to all users couple times. If you didn't use Lucy for a while and it hasn't been auto-logged out yet, when you come back to search in Lucy, it will show you 0%. It might be related to network switch (wired to wireless) in between? Not sure the exact cause yet. But every time it happens, user needs to log out and log back in again.

**Comment by LucyPilot** [comment]
I found out that it is definitely related to the network switch. Every time I change from wired to wireless, if I had a tab logged in for Lucy, it will start showing me 0% on searching and keeps spinning. If I refresh, it will show the double scrolling bar and show me there is an error happened. I have to log out and re-login.

**Comment by LucyPilot** [comment]
Also, if I lock my laptop when I has a Lucy window open. Then I come back unlock my laptop and go back to Lucy, it will keep spinning and show me 0% processing.

**Comment by LucyPilot** [comment]
Another issue happened to me every Monday, I found out it happens to me sometimes in the weekdays as well. If I leave a Lucy window open without logging it out. And shut down my laptop. The next day I use it, Lucy doesn't ask me for login. It will auto-log me in. But after I ask a question, it will keep spinning and showing 0% processing. Or it will show me the answer, but has an error happened message on the left panel.

**Comment by MikeMoravec45** [comment]
LAD-1997 ticket logged, prioritization pending.

**Comment by MikeMoravec45** [comment]
Gem, are you still experiencing this? If so, let's get something scheduled to troubleshoot with a developer next Monday.

**Comment by LucyPilot** [comment]
Mike, I haven't experienced this for a while. Maybe it is because I know how to avoid it. But I can give it a try tonight, and see if this issue comes back again or not.

**Comment by LucyPilot** [comment]
I am not experiencing this any more.
