### ISSUE TITLE
Video issues. Important for CIOC presentation

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#71]
1. Everytime when I on Insights tab to see the metadata, video always auto-plays from the beginning.
2. keyword is not preset in the view.
3. If I choose to show keyword, video will be muted sometimes.

**Comment by MikeMoravec45** [comment]
Several tickets created for these:
LAD-1962 (insights button auto-plays to beginning
LAD-1649 (keyword bugs)

**Comment by MikeMoravec45** [comment]
Gem, I have escalated both these items to see whether we can fix prior to the CIOC presentation.

**Comment by MikeMoravec45** [comment]
We are currently working through these with Microsoft's support team.

**Comment by MikeMoravec45** [comment]
Update: we are setting up a meeting with them (hopefully early next week). Will keep you posted.

**Comment by MikeMoravec45** [comment]
These are fixed now.
