### ISSUE TITLE
Duplicate answer units from same source or different source

### ISSUE THREAD

**Issue by xiaozhixiaozhen** [LucyPilot/Issues-Tracking#72]
Users feedback: Duplicate results were given in every set of the 10 answers to every question. This is from the IMG group.
This happens to IPS group as well, that is because we had files in two source systems. But I thought if we delete them, they will be cleared out from Lucy.

**Comment by LucyPilot** [comment]
Here are the example questions:
1. When did DPIM features turned in production
2. What is the transaction method for repayment cleared suspense
3. What is the role for billings admin in Nationwide Cloud

**Comment by MikeMoravec45** [comment]
As discussed, these are due to moving files between folders before removing from Box. File maintenance will be improved as we deliver upcoming integrations.
