### ISSUE TITLE
Left panel bar is defaulted to be scrolled to the bottom

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#79]
After I log into Lucy or I asked a new question, left panel is always scrolled to the bottom automatically.

**Comment by LucyPilot** [comment]
[scroll bar issue.zip](https://github.com/LucyPilot/Issues-Tracking/files/3610799/scroll.bar.issue.zip)

**Comment by MikeMoravec45** [comment]
This is in progress. Estimated delivery 10/28
