### ISSUE TITLE
Video is not loading

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#81]
![image](https://user-images.githubusercontent.com/50414677/65259610-edda3a00-dad2-11e9-88e7-57174752278c.png)

**Comment by MikeMoravec45** [comment]
This may be related to how many video answer units are loading. Do load balance testing.

**Comment by MikeMoravec45** [comment]
Video loading issue resolved. Please re-open for new occurrences post-12/1/19.
