### ISSUE TITLE
GitHub integration bugs

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#84]
- [ ] page through doesn't work, especially typing in the page number
- [ ] formatting is not good, doesn't match the original source.
- [ ] images are not loaded
- [ ] videos are not loaded
- [ ] If I ask a relevant question, it still shows me the answer I rated high for previous questions. Similar to the WFH team's feedback.

**Comment by MikeMoravec45** [comment]
Let's review these items once we have access to GitHub and have your content ingested through there.

**Comment by LucyPilot** [comment]
I tested GitHub file formatting again. It still has some overlap. Example: how to create rds postgres database, the first and third answer units are still having overlapped context. The 5th, 7th, 8th, 9th, 10th answer units are still not showing the images.

**Comment by LucyPilot** [comment]
Will test again after removing the old content and reloading them once they are cleared out from Lucy.

**Comment by LucyPilot** [comment]
Lower the priority due to lacking of access to GitHub.
