### ISSUE TITLE
Similar question about different companies but finding the exact same answer

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#89]
Example from IRM Alison:
1. Does solidifi have a password policy
2. Does Five9 have a password policy

If I happen to find the answers for No.1 and give them ratings. When I ask No.2, Lucy still gives me same answers for No.1.

**Comment by LucyPilot** [comment]
this is related to #55  Different questions with similar words, Lucy still provides the same answer.

**Comment by MikeMoravec45** [comment]
Research for this is planned for the upcoming sprint. Estimated date for research results October 28.

**Comment by MikeMoravec45** [comment]
Hi Gem, 
I thought I had mentioned this, but don't see the note: This research was pushed to the following sprint, new estimate for expected results is 11/15/19

**Comment by MikeMoravec45** [comment]
Hi Gem, 
The work I described in our last meeting was in the latest production push on 1/9 (last Thursday).

LAD-2450. 
We adjusted the similarity and relevancy scores to improve the results when searching similar questions. 

I am closing this ticket. If you continue to experience issues with new question pairs, let's reopen another ticket.

Thanks,
Mike
