### ISSUE TITLE
Overlapped content on answer unit

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#92]
Example, ask lucy " what are the lucy pilots responsibilities", some of the answer units are having overlapped content on the page.

**Comment by LucyPilot** [comment]
Equals 3 will reprocess any specific folders which have overlapped content files. 
Mike will mention this to all upcoming onboarding sessions. 
I will test it after Mike reprocesses the file back to Lucy.

**Comment by Zach-Meierhofer-Equals-3** [comment]
Reprocessing with the updates have been greatly improving instances of this issue. After reprocessing is complete if issue persists please let us know.

**Comment by MikeMoravec45** [comment]
The file in the example has been reprocessed. Asking the original question shows the content without overlap. 
![image](https://user-images.githubusercontent.com/50464703/70081001-42b72800-15cd-11ea-9771-1903fdba6785.png)
Closing. If more files with overlap arise, please let me know and I will get them reprocessed.
