### ISSUE TITLE
Document switched in SharePoint integration

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#94]
when I ask how to calculate CVAT? I am looking for document 7702 rules.docx. I got it in the answer units. But when I click to switch to next page, it switched to a totally different document. I checked all the answers, they all have the same issue. Sometimes, every single page represents a different document. 
a.	Information that might help from other examples.
1.	Go to https://nationwide365test.sharepoint.com/sites/LucyPublicTesting/
2.	Find documents/ips life/life product/life product info/NW YourLife IUL Accumulator.pdf.
3.	The page number on the bottom shows 1 of 36, but on the top right, there is a previous, next arrows, they are representing to navigate to previous or next documents on this folder instead of paging through within the document. Maybe when your team uses the API, they used that, so it caused the switching document thing. Just a guess. Another example, ask how to generate context diagram of an app. You will see the document switch.

**Comment by MikeMoravec45** [comment]
LAD-2390 is prioritized in the current sprint. Estimated resolution: 11/18/19

**Comment by MikeMoravec45** [comment]
This is built and tested. Pending migration to production.

**Comment by MikeMoravec45** [comment]
This was pushed to production on 12/23/19. Please open new ticket if issue persists.
