### ISSUE TITLE
"Your Research" question is not updated in real-time

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#97]
The section on the homepage that says “Your Research” is not updating real time. We had to close out of the browser and then reopen it. Should it update real time?

**Comment by LucyPilot** [comment]
Mike gave us an update about this issue: "The current design is to update this section after each new session. There is a ticket in the backlog to switch this to real-time updates"

**Comment by Zach-Meierhofer-Equals-3** [comment]
Ticket **LAD-2253 Refresh Homepage Questions During Session**

Moved to **high priority** to reflect change in Github

**Comment by MikeMoravec45** [comment]
Scheduled, estimated delivery, early December.

**Comment by MikeMoravec45** [comment]
Built and tested. Will refresh upon clicking home. Pending migration.

**Comment by MikeMoravec45** [comment]
This was pushed to production on 12/23/19. Please open new ticket if issue persists.
