### ISSUE TITLE
Pictures are not loaded

### ISSUE THREAD

**Issue by LucyPilot** [LucyPilot/Issues-Tracking#99]
Pictures are not loaded. Question: how to match new relic incidents to ServiceNow incidents?

**Comment by MikeMoravec45** [comment]
This work is done in production and ready for testing. Please validate and close when possible.

**Comment by LucyPilot** [comment]
I asked the same question in Lucy today. The answer showed up in Lucy answer unit is not matching the answer in original system AnswerHub. Here is the answer I got from Lucy.
![image](https://user-images.githubusercontent.com/50414677/72015521-e4b2db80-322f-11ea-80df-add505c65d20.png)
But here is the answer from AnswerHub:
![image](https://user-images.githubusercontent.com/50414677/72015545-f2686100-322f-11ea-9705-4516c2117920.png)

**Comment by LucyPilot** [comment]
This is fixed.
